# helm/demo-app/templates/mongo-deployment.yaml
{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: {{ template "demo-app.name" . }}
    component: mongo
spec:
  selector:
    matchLabels:
      app: {{ template "demo-app.name" . }}
      component: mongo
  template:
    metadata:
      labels:
        app: {{ template "demo-app.name" . }}
        component: mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: 27017
        {{- if .Values.mongodb.persistence.enabled }}
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
        {{- end }}
---
# helm/demo-app/templates/mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: {{ template "demo-app.name" . }}
    component: mongo
spec:
  selector:
    app: {{ template "demo-app.name" . }}
    component: mongo
  ports:
  - port: 27017
    targetPort: 27017
{{- end }}